## NUMPY Assignment

In [1]:
import numpy as np

#create a numpy array of 5 zeros.
    #check datatype, itemsize and shape of above

lst = np.zeros(5, dtype='int8')

print(lst)
print(lst.dtype)
print(lst.itemsize)
print(lst.shape)

[0 0 0 0 0]
int8
1
(5,)


In [2]:
##create a numpy array of ones of shape (5,4)

lst = np.ones((5,4), dtype='int8')

print(lst)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [3]:
#create a matrix of shape 4,5 with numbers from 1-20

lst = np.arange(1,21)
a=lst.reshape(4,5)
print(lst)
print()
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
#multiply all elements of above array by 10

b=a*10
print(b)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [5]:
#print odd elements from array

print(lst[lst%2==1])

[ 1  3  5  7  9 11 13 15 17 19]


In [6]:
#replace all even elements by their negative

print(-lst[lst%2==0])

[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [7]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

M1 = np.arange(1,17)
M1.resize(4,4)

print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
#create a transpose of above matrix call it M2

M2 = M1.T

print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [9]:
#find sum of above matrix M3 = (M1 + M2)

M3 = M1+M2
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [10]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1

MT1=M3.T
print(MT1)
print()
print(M3==MT1)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [11]:
#- find diffrence of M4 = (M1 - M2)
M4=M1-M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [12]:
#- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

MT2=M4.T
print(MT2)
print()
print(M4==MT2)
print()
print(M4==-MT2)

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [13]:
#- create a matrix (3x4) R1 of random numbers between 10-40

R1 = np.random.randint(10,40,12)
R1.resize(3,4)
print(R1)

[[19 32 32 30]
 [36 18 20 22]
 [26 15 35 19]]


In [14]:
#- find min and max column wise

print(R1.min(0))
print(R1.max(0))

[19 15 20 19]
[36 32 35 30]


In [15]:
#- replace the last column with sum of all the columns
print(R1)


[[19 32 32 30]
 [36 18 20 22]
 [26 15 35 19]]


In [16]:
#- replace all even elements with nan in R1
R1 = np.random.randint(10,40,12)
R1.resize(3,4)
print(R1)
print()
#prit(R2)
#R2=np.nan(R1[R1%2==0])

#print(R1[R1%2==0]=np.nan)

[[28 16 26 14]
 [23 37 22 14]
 [22 11 26 23]]



In [17]:
#- count number of nan in R1
print(R1)
#print(R1.count(nan))

[[28 16 26 14]
 [23 37 22 14]
 [22 11 26 23]]


In [18]:
#- check output of this code  

a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
