## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [4]:
# Create a numpy array of 5 zeros.
# Check datatype, itemsize and shape of above
import numpy as np
a = [0,0,0,0,0]

n=np.array(a)
print(n)
print()
print('Type of numpy array print below')
print(type(n))
print()
print('Type of numpy array DATA TYPE print below')
print(n.dtype)
print()
print('Type of numpy array ITEM SIZE print below')
print(n.itemsize)
print()
print('Type of numpy array SHAPE print below')
print(n.shape)
print()
print('Type of numpy array SIZE print below')
print(n.size)

[0 0 0 0 0]

Type of numpy array print below
<class 'numpy.ndarray'>

Type of numpy array DATA TYPE print below
int32

Type of numpy array ITEM SIZE print below
4

Type of numpy array SHAPE print below
(5,)

Type of numpy array SIZE print below
5


In [5]:
# Create a numpy array of ones of shape (5,4) 5 rows and 4 columns


a= range(1,21,1)
n=np.array(a)
print(n)
print(type(n))

n1=n.reshape(5,4)
print(n1)
print(n1.shape)
print(n1.itemsize)
print(n1.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
(5, 4)
4
int32


In [2]:
# Ceate a matrix of shape 4,5 with numbers from 1-20
import numpy as np
a=range(1,21,1)
n=np.array(a)
print(n)
n2=n.reshape(4,5)
# print(n.reshape(4,5))
print(n2)
print(n2.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [3]:
# Multiply all elements of above array by 10
n3=n2*10
print(n3)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [4]:
# Print odd elements from array
print(n2)
n4=n2.reshape(20)
print(n4)
n5=n4[n4%2!=0]
print(n5)
print(n5.shape)
print(n5.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]
(10,)
[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [22]:
# Replace all even elements by their negative
n3=n2
n4=n3
print(n2)
print(n3)
r=n3%2
r1=r==0
n3[r1]=-n3[r1]
print(n3)
# print(n2[r1])
# n5=n2[r1]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [39]:
# Create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
import numpy as np
M1=((np.arange(1,17)).reshape(4,4))
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [36]:
# Create a transpose of above matrix call it M2
M2=(M1.T)
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [37]:
#Find sum of above matrix M3 = (M1 + M2)
print(M1)
print()
print(M2)
print()
M3=M1+M2
print(M3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [50]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1=M3.T
print(MT1)
if M3.all()==MT1.all():
    print (True) 


[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
True


In [52]:
# find diffrence of M4 = (M1 - M2)
print(M1)
print()
print(M2)
print()
M4=M1-M2
print(M4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [57]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2=M4.T
print(MT2)
if M4.all()==MT2.all():
    print(True)
if M4.all()==(MT2*-1).all():
     print(True)

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]
True
True


In [1]:
# Create a matrix (3x4) R1 of random numbers between 10-40
import numpy as np
n=np.random.randint(10,40,12)
print(n)
np1=n.reshape(3,4)
print(np1)

[29 19 37 30 20 34 32 26 36 33 28 10]
[[29 19 37 30]
 [20 34 32 26]
 [36 33 28 10]]


In [2]:
# find min and max column wise
print(np1)
x=len(np1)
y=len(np1[1])
out_lst_max=[]
out_lst_min=[]

for i in range(0,y):
    inp_lst_col=np1[:,i]
#     print(inp_lst_col)
    max_num=inp_lst_col[0]
    min_num=inp_lst_col[0]
    for j in inp_lst_col:
        if max_num < j:
            max_num=j
        elif min_num>j:
            min_num=j
    out_lst_max.append(max_num)
    out_lst_min.append(min_num)
    max_num=0
    min_num=0
    inp_lst_col=[]
print('List of max numbers')
print(out_lst_max)
print('List of min numbers')
print(out_lst_min)

[[29 19 37 30]
 [20 34 32 26]
 [36 33 28 10]]
List of max numbers
[36, 34, 37, 30]
List of min numbers
[20, 19, 28, 10]


In [3]:
# Replace the last column with sum of all the columns
print(np1)
print(np1[:,3])
last_col_lst=np1[:,3]
print(last_col_lst)
x=len(np1)
print(x)
y=len(np1[1])-1
print(y)
asum=0

for i in range (0,y):
    var=last_col_lst[i]
    asum=asum+var
    var=0
print(asum) 
for j in range (0,y):
    np1[:,y][j]=asum

print(np1)

[[29 19 37 30]
 [20 34 32 26]
 [36 33 28 10]]
[30 26 10]
[30 26 10]
3
3
66
[[29 19 37 66]
 [20 34 32 66]
 [36 33 28 66]]


In [ ]:
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1

In [57]:
# create a matrix (3x4) R1 of random numbers between 10-40
import numpy as np3
ax=np.random.randint(10.0,40.0,12)
# ax=ay(dtype='float')

ax[1]= 23.00
print(ax)
print(ax[1])
R1=ax.reshape(3,4)
print(R1)
print(R1.itemsize)
print(R1.dtype)

[15 23 29 31 12 31 12 25 29 20 23 25]
23
[[15 23 29 31]
 [12 31 12 25]
 [29 20 23 25]]
4
int32


In [66]:
# Replace all even elements with nan in R1
x=len(R1)
y=len(R1[1])
print(x,y)
for i in range (0,4):
    for j in range (0,3):
        print(R1[j,i:i+1])
        p=R1[j,i:i+1]%2
        if p == 0:
            R1[j,i:i+1]= 0
print(R1)

print(np.where(R1==0))
print(np.count_nonzero(R1))
print('Number of zeroes')
print((R1.size)-(np.count_nonzero(R1)))

3 4
[15]
[0]
[29]
[23]
[31]
[0]
[29]
[0]
[23]
[31]
[25]
[25]
[[15 23 29 31]
 [ 0 31  0 25]
 [29  0 23 25]]
(array([1, 1, 2], dtype=int64), array([0, 2, 1], dtype=int64))
9
Number of zeroeszeroes
3


In [68]:
a1 = np.arange(1,10).reshape(3,3)
print('a1')
print(a1)
print()
a2 = np.arange(11,20).reshape(3,3)
print('a2')
print(a2)
print()
a3 = np.append(a1,a2)
print('a3 which is append(a1,a2)')
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print('a3 which is append(a1,a2, axis = 0)')
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print('a3 which is append(a1,a2, axis = 1)')
print(a3)
print()

a1
[[1 2 3]
 [4 5 6]
 [7 8 9]]

a2
[[11 12 13]
 [14 15 16]
 [17 18 19]]

a3 which is append(a1,a2)
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

a3 which is append(a1,a2, axis = 0)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

a3 which is append(a1,a2, axis = 1)
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]

