## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


###### create a numpy array of 5 zeros.check datatype, itemsize and shape of above

In [1]:
import numpy as np
n=np.zeros((1,5),dtype='int32')
print(type(n))
print(n.dtype)
print(n.itemsize)
print(n.shape)

<class 'numpy.ndarray'>
int32
4
(1, 5)


###### create a numpy array of ones of shape (5,4)


In [2]:
n1=np.ones((5,4),dtype='int8')
print(n1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


###### create a matrix of shape 4,5 with numbers from 1-20
###### multiply all elements of above array by 10
###### print odd elements from array

In [3]:
n3=np.arange(20)
n3.resize(4,5)
print(n3)
print()
print(n3*10)
print()
for i in range(4):
    for j in range(5):
        if n3[i,j]%2!=0:
            print(n3[i,j])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]

1
3
5
7
9
11
13
15
17
19


###### replace all even elements by their negative

In [4]:
n3=np.arange(20)
n3.resize(4,5)
for i in range(4):
    for j in range(5):
        if n3[i,j]%2==0:
            n3[i,j]=-n3[i,j]
print(n3)

# r[]=n3[i,j]%2==0
# print(n3(r))

[[  0   1  -2   3  -4]
 [  5  -6   7  -8   9]
 [-10  11 -12  13 -14]
 [ 15 -16  17 -18  19]]


#### create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
###### create a transpose of above matrix call it M2
###### find sum of above matrix M3 = (M1 + M2)
###### Find Transpose of M3, Call it MT1. Check if M3 == MT1
###### find diffrence of M4 = (M1 - M2)
###### Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

In [5]:
m1=(np.arange(1,17))
m1.resize(4,4)
m2=m1.T
m3=m1+m2
print((m3==m3.T).all())
m4=m1-m2
print()
print((m4==m4.T).all())
print()

print((m4==-m4.T).all())

True

False

True


###### create a matrix (3x4) R1 of random numbers between 10-40
###### find min and max column wise
###### replace the last column with sum of all the columns

In [6]:
m=(np.random.randint(10,40,12)).reshape(3,4)
print(m)
print()
for i in range(4):
    print('column wise max values are',m[:,i].max(),end='\t')
    print('column wise min values are',m[:,i].min())

#for replacing last column with sum of all columns
print()
for i in range(3):
    m[i,3]=m[i,0]+m[i,1]+m[i,2]
print(m)

[[32 22 10 24]
 [23 15 25 33]
 [12 19 34 31]]

column wise max values are 32	column wise min values are 12
column wise max values are 22	column wise min values are 15
column wise max values are 34	column wise min values are 10
column wise max values are 33	column wise min values are 24

[[32 22 10 64]
 [23 15 25 63]
 [12 19 34 65]]


###### create a matrix (3x4) R1 of random numbers between 10-40
###### replace all even elements with nan in R1
###### count number of nan in R1

In [42]:
n=(np.random.randint(10.0,40.0,12,dtype='int32')).reshape(3,4)
a=np.array(n,dtype='float')
count=0
for i in range(3):
    for j in range(4):
        if a[i,j]%2==0:
            (a[i,j])=np.nan
            count+=1
            

print(a,count)

b=print(np.isnan(a).sum())

[[nan 27. 27. nan]
 [29. 15. nan 13.]
 [31. 39. nan 23.]] 4
4


###### check output of this code


In [22]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
