In [ ]:
print("abcd")

In [13]:
a = list(range(10,20,2))
print(a)

[10, 12, 14, 16, 18]


In [3]:
print(a)

[10, 12, 14, 16, 18]


In [7]:
r = a[1] # indexing
print(r)

12

In [15]:
a = list(range(10,20,2))
print(a)
print(a[1:3])

[10, 12, 14, 16, 18]
[12, 14]


### Behaviors

In [16]:
a = [True, 11, "abcd", []]
print(a)
print(a[1])
print(a[2])
print(a[3])
print(a[:1])

[True, 11, 'abcd', []]
11
abcd
[]
[True]


In [79]:
import numpy as np

In [21]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [27]:
print(np.FLOATING_POINT_SUPPORT)
print(np.isnan(11))

1
False


In [26]:
print(np)

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
<module 'numpy.random' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>


In [28]:
print(list("abcd"))

['a', 'b', 'c', 'd']


In [29]:
a = [10,20,30,40,50]

n = np.array(a)
print(n, type(n))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [30]:
print(n[1], type(n[1]))
print(n[1:], type(n[1:]))

20 <class 'numpy.int32'>
[20 30 40 50] <class 'numpy.ndarray'>


In [34]:
n = np.array(range(10,100,10))
print(n)
print()
print(n.dtype)
print(n.size)
print(n.shape)

[10 20 30 40 50 60 70 80 90]

int32
9
(9,)


In [35]:
n = np.array(range(10,100,10), dtype='int64')
print(n) # n is vector
print()
print(n.dtype)
print(n.size)
print(n.shape)
i = 10 # scalar

[10 20 30 40 50 60 70 80 90]

int64
9
(9,)


In [ ]:
print(1)
print((1))
print((1))

In [39]:
# int vs float
a =  np.array([1,2,3, 2000], dtype = np.int8)
print(a.dtype)
print(a.itemsize)
print(a)

int8
1
[  1   2   3 -48]


In [45]:
# int vs float
a =  np.array([1,2,3, 2000])
print(a.dtype)
print(a.itemsize)
print(a)
print(a.flags)
print(a.ndim)

int32
4
[   1    2    3 2000]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
1


In [44]:
# int vs float
a =  np.array([1,2.5,3, 2000])
print(a.dtype)
print(a.itemsize)
print(a)
print(a[1])

float64
8
[1.0e+00 2.5e+00 3.0e+00 2.0e+03]
2.5


In [42]:
# int vs float
a = np.array([1,"2.5",3, 2000])
print(a.dtype)
print(a.itemsize)
print(a)

<U11
44
['1' '2.5' '3' '2000']


In [43]:
# int vs float
a =  np.array([1,[],"2.5",3, 2000])
print(a.dtype)
print(a.itemsize)
print(a)

object
8
[1 list([]) '2.5' 3 2000]


In [55]:
a = np.arange(1,13)
print(a, type(a))

print()
b = a.reshape((3,4))
print(b)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [65]:
r = [  [1,2], [3,4], [6, 7] ]
a = np.array(r)
print(a)

print()
print(type(a), type(a[0]))
print(a[0])
print(a.shape)

[[1 2]
 [3 4]
 [6 7]]

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1 2]
(3, 2)


In [67]:
r = [  [1,2], [3,4], [6, 7] ]
a = np.array(r)
print(a)

print()
print(a.T) # transpose

[[1 2]
 [3 4]
 [6 7]]

[[1 3 6]
 [2 4 7]]


In [72]:
a = np.arange(1,13)
print(a, type(a))

print()
b = a.reshape((3,4))
print(b)

print()
b = a.reshape((3,2,2))
print(b)

print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [75]:
a = np.arange(1,13)
print(a, type(a))
print()
b = a.resize((3,5))
print(b)
print(a)

a.resize((3,3))
print()
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>

None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  0  0  0]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
r = np.random.randint(10,20 ,100)
print(r)
r.resize(10,10)
print(r)

[11 10 17 12 11 19 14 17 11 14 12 18 12 14 11 11 15 17 17 10 19 18 19 10
 17 16 10 11 18 19 12 10 17 10 17 10 18 16 19 17 12 17 16 17 10 12 19 15
 17 12 18 17 19 18 11 17 11 19 18 12 11 11 17 18 17 14 13 17 16 16 18 18
 14 10 10 16 14 11 11 11 15 18 11 14 11 16 12 16 12 19 11 12 18 10 19 18
 12 18 13 14]
[[11 10 17 12 11 19 14 17 11 14]
 [12 18 12 14 11 11 15 17 17 10]
 [19 18 19 10 17 16 10 11 18 19]
 [12 10 17 10 17 10 18 16 19 17]
 [12 17 16 17 10 12 19 15 17 12]
 [18 17 19 18 11 17 11 19 18 12]
 [11 11 17 18 17 14 13 17 16 16]
 [18 18 14 10 10 16 14 11 11 11]
 [15 18 11 14 11 16 12 16 12 19]
 [11 12 18 10 19 18 12 18 13 14]]


In [80]:

r = np.random.randint(10,20 ,20)
print(r)
r.resize(4,5)
print(r)

print()
print(r.T)

[18 11 10 16 11 16 15 19 14 11 19 12 16 13 16 10 13 17 16 11]
[[18 11 10 16 11]
 [16 15 19 14 11]
 [19 12 16 13 16]
 [10 13 17 16 11]]

[[18 16 19 10]
 [11 15 12 13]
 [10 19 16 17]
 [16 14 13 16]
 [11 11 16 11]]


In [87]:
a =np.zeros((2,3), dtype='int8')
print(a)
a =np.ones((2,3), dtype='int8')
print(a)
r = a*10

print()
print(r)
print(a)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]

[[10 10 10]
 [10 10 10]]
[[1 1 1]
 [1 1 1]]


In [102]:
a1 = np.arange(1,7).reshape((2,3))
a2 = np.arange(11,17).reshape((2,3))
a3 = np.arange(21,24)
print(a1)
print(a2)
print(a3)

print()
print(a1*a2)

print()
print(a3*a1)

print()
print(a1*a3)

print() # matrix multiplication
print(np.matmul(a1,a3))

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
[21 22 23]

[[11 24 39]
 [56 75 96]]

[[ 21  44  69]
 [ 84 110 138]]

[[ 21  44  69]
 [ 84 110 138]]

[134 332]


In [108]:
# linspace
a = np.linspace(1,8,8, dtype='int8') # AP
print(a)
a

[1 2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [ ]:
# __str__
# __repr__

In [111]:
a = np.arange(10,20)
print(a)

print(a[1])
print(a[1::2])
print(a[::-2])

[10 11 12 13 14 15 16 17 18 19]
11
[11 13 15 17 19]
[19 17 15 13 11]


In [117]:
a = np.arange(10,20)
print(a)
r = a%2
print(r)
r1 = r == 0
print(r1)
print(a[r1])

print(a[a%3 == 0])

# print( [10,20] == 10)

[10 11 12 13 14 15 16 17 18 19]
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[10 12 14 16 18]
[12 15 18]


In [126]:
a = np.arange(10,20)
print(a)
r = ((a%3) == 0)
print(r)
print(~r)
print(a[a%3 == 0])

[10 11 12 13 14 15 16 17 18 19]
[False False  True False False  True False False  True False]
[ True  True False  True  True False  True  True False  True]
[12 15 18]


In [128]:
a = np.array([10,20,30])
print(a[ [True, False, True] ])

[10 30]


In [131]:
s = input("Enter something")

nums = [int(n) for n in s.split()]

a = np.array(nums)
print(a)

Enter something10 20 30
[10 20 30]


In [138]:
print(type(np.nan))

<class 'float'>


In [147]:
a1 = np.array([10,20,30.0])
a2 = np.array([10,20,30.0])

a1[1] = np.nan
print(a1, a2)
print()
print(a1.sum())
print(a2.sum())

print()
print(a1.sum())
print(a2.sum())

print(np.nan == np.nan)
print(np.nan < np.nan)
print(np.nan == 10)
print(np.nan == np.int8(10))
print(np.nan + np.int8(10))

[10. nan 30.] [10. 20. 30.]

nan
60.0

nan
60.0
False
False
False
False
nan


In [153]:
a1 = np.array([10,20,30.0, np.nan])
a1[1] = np.nan

print(a1)
print(np.isnan(a1))

a1[np.isnan(a1)] = 100
print(a1)

[10. nan 30. nan]
[False  True False  True]
[ 10. 100.  30. 100.]


In [154]:
a = [1,2,3]
a[0] = 100
print(a)

[100, 2, 3]


In [167]:
a = np.array([1,2,3])
print(a.all()) # and
print(a.any()) # or 

print()
a = np.array([0,2,3])
print(a.all()) # and
print(a.any()) # or

print()
a = np.array([0,0,0, np.nan])
print(a)
print(a.all()) # and
print(a.any()) # or

print()
a = np.array([np.nan]*4)
print(a)
print(a.all()) # and
print(a.any()) # or

print()
print(np.bool(np.nan))

True
True

False
True

[ 0.  0.  0. nan]
False
True

[nan nan nan nan]
True
True

True


In [180]:
a = np.arange(1,13).reshape((3,4))*10
print(a)

print("\n rows", a[0])
print("\n rows", a[0:2])


print("\n Col", a[:, 0]) # a[r][c]
print("\n Col", a[:,0:2])
print("\n Col", a[:,0:2].T)

print()
print("\n Col", a[1,2])
print("\n Col", a[0:2,2:])

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

 rows [10 20 30 40]

 rows [[10 20 30 40]
 [50 60 70 80]]

 Col [10 50 90]

 Col [[ 10  20]
 [ 50  60]
 [ 90 100]]

 Col [[ 10  50  90]
 [ 20  60 100]]


 Col 70

 Col [[30 40]
 [70 80]]


In [186]:
a = np.arange(1,13).reshape((3,4))*10
print(a)
print(a[ ((1,2,2),(0,3,2)) ])

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[ 50 120 110]


In [191]:
a = np.arange(10,20).reshape(2,5)
print(a)
print()
print(a%2 == 0)

i = np.where(a%2 == 0)
print(i)

print(a[ i ])

[[10 11 12 13 14]
 [15 16 17 18 19]]

[[ True False  True False  True]
 [False  True False  True False]]
(array([0, 0, 0, 1, 1], dtype=int64), array([0, 2, 4, 1, 3], dtype=int64))
[10 12 14 16 18]


In [212]:
#r  = np.loadtxt('test.csv', delimiter=',')
#print(r)

r = np.genfromtxt('test.csv', delimiter=",", dtype=None,  encoding="ASCII")
print(r)
print(type(r[0]))
print(r[1][1])

[( 1,  2,  3, 'a') (11, -1, 22, 'b')]
<class 'numpy.void'>
-1


In [192]:
with open('test.csv', 'w')  as f:
    print("1,2,3", file = f)
    print("11,,22", file = f)